# Декомпозиција пуног ранга

**Садржај:**
1. [Декомпозиција пуног ранга](#Декомпозиција-пуног-ранга)
1. [Тихе врсте и колоне](#Тихе-врсте-и-колоне)

In [1]:
import numpy as np
import numpy.random as rndm
from scipy.linalg import null_space
import sympy as sym
import numpy.random as rndm

***

Факторизација матрица, или декомпозиција матрица, значи растављање матрице у производ две или више матрица. Том приликом су матрице чиниоци са специјално бираним особинама. Тако је нпр. дијагонализација матрица предствљање квадратне матрице у облику производа $A=TDT^{-1}$ на основу спектралних особина матрице $A.$ Циљ факторизације неке матрице може бити и кодирање одређеног нумеричког поступка и резултат добијеног њиме. Нумерички алгоритми који користе линеарне комбинације фиксног скупа вектора су директно представиви у облику производа две матрице. Примери таквих алгоритама су Гаусов и Грам-Шмит. 

Циљ факторизације може да буде и "оптимизација" неких карактеристика података. Приступ декомпозицији овог типа у начелу гласи: 
>пронаћи декомпозицију матрице $A\in\mathcal{M}_{m\times n}$ на производ две матрице $X\in\mathcal{M}_{m\times r}$ и $Y\in\mathcal{M}_{r\times n}$  тако да је $A\approx XY.$ 

Број $r<<m,n$ у декомпозицији је параметар који се зове ранг факторизације. Он служи за контролу концизности факторизације с обзиром да је укупан број елемената фактора $X$ и $Y$ једнак $r(m+n).$ Ова вредност је много мања од полазног броја података матрице $A,$ $mn.$ Одлука о величини ранга $r$ доноси се на основу жељених својстава апроксимације $XY.$ 

**Пример 1.** Матрица $A$ има факторизацију $A=uv^T$ и представља матрицу ранга $1.$

\begin{align} 
A=uv^T&=\begin{bmatrix} x_0\\x_1\\ \vdots\\ x_{m-1}\end{bmatrix}\,
	\begin{bmatrix} y_0&y_1&\dots&y_{n-1}\end{bmatrix}=
	\begin{bmatrix} x_0y_0&x_0y_1&\dots &x_0y_{n-1}\\
	x_1y_0&x_1y_1&\dots &x_1y_{n-1}\\ 
	\vdots&\vdots & &\vdots\\
	x_{m-1}y_0&x_{m-1}y_1&\dots &x_{m-1}y_{n-1}\end{bmatrix}\\
&=\begin{bmatrix}
	x_0\begin{bmatrix} y_0&y_1&\dots&y_{n-1}\end{bmatrix}\\
	x_1\begin{bmatrix} y_0&y_1&\dots&y_{n-1}\end{bmatrix}\\ \vdots\\
	x_{m-1}\begin{bmatrix} y_0&y_1&\dots&y_{n-1}\end{bmatrix}\\
	\end{bmatrix}   
=\begin{bmatrix} y_0 \begin{bmatrix} x_0\\x_1\\ \vdots\\ x_{m-1}\end{bmatrix}&
	y_1 \begin{bmatrix} x_0\\x_1\\ \vdots\\ x_{m-1}\end{bmatrix}& \dots&
	y_{n-1} \begin{bmatrix} x_0\\x_1\\ \vdots\\ x_{m-1}\end{bmatrix}
	\end{bmatrix},\\
&\mathcal{R}(A)=\mathcal{L}(u),\qquad \mathcal{R}(A^T)=\mathcal{L}(v)\qquad
\Longrightarrow\quad {\rm rang}(A)=1.
\end{align}

In [2]:
u=np.arange(-7,11,0.37)
v=np.linspace(-3.65,8.19)

In [3]:
m=u.size
n=v.size
m,n

(49, 50)

In [4]:
A=np.outer(u,v)
A.size, m+n

(2450, 99)

In [5]:
np.linalg.matrix_rank(A), A.shape

(1, (49, 50))

У приказаном случају факторизација матрице $A$ је тачна. Ако додамо "шум" елементима матрице $A$ остаје процена $A\approx uv^T.$ Квалитет апроксимације матрица изражава се нормом матрица, и то је једна од наредних тема. 

У кодним ћелијама које следе коришћени су позиви уграђених функција за израчунавање неких од стандардних норми вектора. Фробенијусова норма матрица је Еуклидова норма одговарајућих векторизованих матрица. Норме вектора су употребљене за поређење разлика између матрице $A$ са шумом и матрице $uv^T.$ 

In [6]:
Asum=A+0.001*rndm.randn(m,n)

In [7]:
np.linalg.matrix_rank(Asum)

49

In [8]:
np.linalg.norm(Asum.reshape(m*n,)-A.reshape(m*n,))

0.04946589382406907

In [9]:
np.linalg.norm(Asum.reshape(m*n,)-A.reshape(m*n,))/np.linalg.norm(Asum.reshape(m*n,)) #relativno odstupanje

4.319868719893951e-05

In [10]:
np.linalg.norm(Asum.reshape(m*n,)-A.reshape(m*n,),np.inf)

0.003983022322392622

In [11]:
np.linalg.norm(Asum.reshape(m*n,)-A.reshape(m*n,),np.inf)/np.linalg.norm(Asum.reshape(m*n,),np.inf) 
#relativno odstupanje

4.5197806909000576e-05

***

**Задатак 1.** Изразити матрице $A=\begin{bmatrix}1&2&3&4\\0&0&0&0\end{bmatrix}$ и $B=\begin{bmatrix}1&2&3&4\\0&0&0&0\\1&2&3&4\end{bmatrix}$ преко спољашњег производа два вектора. Ког су ранга матрице $A$ и $B?$

**Решење :**

$A=\begin{bmatrix}1&2&3&4\\0&0&0&0\end{bmatrix}=\left[\begin{array}{cccc}
1\cdot\begin{bmatrix}1\\0\end{bmatrix}&2\cdot\begin{bmatrix}1\\0\end{bmatrix}&3\cdot\begin{bmatrix}1\\0\end{bmatrix}
&4\cdot\begin{bmatrix}1\\0\end{bmatrix}
\end{array}\right]=\begin{bmatrix}1\\0\end{bmatrix}\begin{bmatrix}1&2&3&4\end{bmatrix}$ 

Провера:

In [12]:
a=np.array([1,0])
b=np.array([1,2,3,4])
np.outer(a,b)

array([[1, 2, 3, 4],
       [0, 0, 0, 0]])

$B=\begin{bmatrix}1&2&3&4\\0&0&0&0\\1&2&3&4\end{bmatrix}=\left[\begin{array}{cccc}
1\cdot\begin{bmatrix}1\\0\\1\end{bmatrix}&2\cdot\begin{bmatrix}1\\0\\1\end{bmatrix}&3\cdot\begin{bmatrix}1\\0\\1\end{bmatrix}
&4\cdot\begin{bmatrix}1\\0\\1\end{bmatrix}
\end{array}\right]=\begin{bmatrix}1\\0\\1\end{bmatrix}\begin{bmatrix}1&2&3&4\end{bmatrix}$

Провера:

In [13]:
a=np.array([1,0,1])
b=np.array([1,2,3,4])
np.outer(a,b)

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

Обе матрице су ранга 1 на основу примера 1.

***

## Декомпозиција пуног ранга

**Дефиниција 1.** За матрицу $A\in\mathcal{M}_{m\times n}$ ранга $r$ декомпозиција пуног ранга је представљање матрице $A$ у облику производа 
$$A=BC,\qquad B\in\mathcal{M}_{m\times r},\ C\in\mathcal{M}_{r\times n},\quad {\rm rang}(B)={\rm rang}(C)=r.$$

***

**Теорема 1.** *Теорема о декомпозицији пуног ранга*

Матрица $A\in\mathcal{M}_{m\times n}$ је ранга $r$ акко постоји декомпозиција пуног ранга матрице $A.$

**Последица 1.** Ако је $A=BC$ декомпозиција пуног ранга матрице $A,$ тада је $A^T=C^TB^T$ декомпозиција пуног ранга матрице $A^T.$

За декомпозицију пуног ранга $A=BC$ важи:
- $\mathcal{R}(A)=\mathcal{R}(B)\quad$ и $\quad\mathcal{R}(A^T)=\mathcal{R}(C^T),$
- $\mathcal{N}(A)=\mathcal{N}(C)\quad$ и $\quad\mathcal{N}(A^T)=\mathcal{N}(B^T).$

***

**Пример 2.** Декомпозиција пуног ранга матрице $A\in\mathcal{M}_{6\times7}$ гласи
$$A=BC=\begin{bmatrix}1&-1&1\\0&1&1\\1&0&-1\\1&1&0\\1&1&1\\0&0&-1\end{bmatrix}
\begin{bmatrix} 1&-1&1&-1&1&-1&1\\ 0&1&1&1&1&1&1 \\ 0&1&-1&1&0&0&0 \end{bmatrix}.$$

In [14]:
B=np.array([[1,-1,1],[0,1,1],[1,0,-1],[1,1,0],[1,1,1],[0,0,-1]])
C=np.array([[1,-1,1,-1,1,-1,1],[0,1,1,1,1,1,1],[0,1,-1,1,0,0,0]])
np.linalg.matrix_rank(B) , np.linalg.matrix_rank(C)

(3, 3)

In [15]:
A=B@C
A.shape , np.linalg.matrix_rank(A)

((6, 7), 3)

In [16]:
A.size, B.size+C.size

(42, 39)

Проверићемо на примеру матрице $A$ једнакости простора колона и врста,
$$\mathcal{R}(A)=\mathcal{R}(B)\ \Longleftrightarrow\ \mathcal{R}(A)=\mathcal{R}([A\,|\, B]),\qquad \mathcal{R}(A^T)=\mathcal{R}(C^T)\ \Longleftrightarrow\ \mathcal{R}(A^T)=\mathcal{R}([A^T\,|\, C^T]).$$

In [17]:
np.linalg.matrix_rank(np.block([A,B]))

3

In [18]:
np.linalg.matrix_rank(np.block([A.T,C.T]))

3

Проверићемо једнакост језгара
$$\mathcal{N}(A)=\mathcal{N}(C),\qquad \mathcal{N}(A^T)=\mathcal{N}(B^T).$$

In [19]:
jezgro=null_space(C)
np.round(A@jezgro,2)

array([[ 0.,  0., -0.,  0.],
       [ 0., -0.,  0.,  0.],
       [-0., -0., -0., -0.],
       [ 0., -0.,  0., -0.],
       [ 0., -0.,  0.,  0.],
       [-0., -0.,  0., -0.]])

In [20]:
jezgro=null_space(B.T)
np.round(A.T@jezgro,2)

array([[ 0., -0., -0.],
       [-0.,  0.,  0.],
       [ 0., -0.,  0.],
       [-0.,  0.,  0.],
       [ 0., -0.,  0.],
       [ 0.,  0.,  0.],
       [ 0., -0.,  0.]])

***

**Задатак 2.** Конструисати матрицу $A\in\mathcal{M}_{4\times3}$ чију базу простора колона чине вектори $v=\begin{bmatrix}1&1&0&0\end{bmatrix}^T$ и $u=\begin{bmatrix}0&1&1&1\end{bmatrix}^T.$

**Rešenje:**

Najjednostavniji način za konstrukciju tražene matrice jeste postavljanje data dva vektora $v$ i $u$ za neke dve kolone matrice $A.$ Za treću kolonu tada treba uzeti neki linearno zavisan vektor, tj. vektor iz prostora $\mathcal{L}(v,u).$ Neki jednostavni primeri su: $\theta,\ v,\ u,\ v+u,\ v-u,\dots$ Na taj način dobijamo različite primere matrice $A$ koja zadovoljava postavljeni uslov:
$$\begin{bmatrix}1&0&0\\1&1&0\\0&1&0\\0&1&0\end{bmatrix},
\begin{bmatrix}1&0&1\\1&1&1\\0&1&0\\0&1&0\end{bmatrix},\begin{bmatrix}1&0&0\\1&1&1\\0&1&1\\0&1&1\end{bmatrix},
\begin{bmatrix}1&0&1\\1&1&2\\0&1&1\\0&1&1\end{bmatrix},\begin{bmatrix}1&0&0\\1&1&0\\0&1&-1\\0&1&-1\end{bmatrix}\dots$$
Takođe, bilo koja permutacija kolona u matricama iz primera daće ponovo matricu koja zadovoljava postavljene uslove. 

Iz teoreme o dekompoziciji punog ranga znamo da sve matrice $A$ koje zadovoljavaju postavljeni uslov $\mathcal{R}(A)=\mathcal{L}(v,u)$ se  dobijaju formulom
$$A=\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}c_{00}&c_{01}&c_{02}\\c_{10}&c_{11}&c_{12}\end{bmatrix},$$
gde je matrica $C=\begin{bmatrix}c_{00}&c_{01}&c_{02}\\c_{10}&c_{11}&c_{12}\end{bmatrix}$ ranga $2.$ To se postiže kada vrste matrice $C$ nemaju proporcionalne komponente, tj kada važi 
$$\begin{bmatrix}c_{00}&c_{01}&c_{02}\end{bmatrix}\neq\lambda\begin{bmatrix}c_{10}&c_{11}&c_{12}\end{bmatrix}.$$

Tako se prethodni primeri matrice $A$ dobijaju dekompozicijama:
\begin{align}
&\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&0&0\\0&1&0\end{bmatrix},
&&\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&0&1\\0&1&0\end{bmatrix},
&&\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&0&0\\0&1&1\end{bmatrix},\\
&\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&0&1\\0&1&1\end{bmatrix},
&&\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&0&1\\0&1&-1\end{bmatrix},\dots
\end{align}

Ukoliko želimo da dobijemo opšti oblik matrice $A=\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}c_{00}&c_{01}&c_{02}\\c_{10}&c_{11}&c_{12}\end{bmatrix},$ možemo da iskoristimo Python paket za simbolička izračunavanja SymPy. Definišemo elemente matrice $C$ kao simbole i primenimo standardne operacije za NumPy nizove. 

In [21]:
c00, c01, c02, c10, c11, c12 = sym.symbols('c00, c01, c02, c10, c11, c12')
B=np.array([[1,0],[1,1],[0,1],[0,1]])
C=np.array([[c00, c01, c02],[c10, c11, c12]])
A=B@C
print(A)

[[c00 c01 c02]
 [c00 + c10 c01 + c11 c02 + c12]
 [c10 c11 c12]
 [c10 c11 c12]]


***

**Zadatak 3.** Konstruisati matricu $A\in\mathcal{M}_{4\times3}$ tako da je $\mathcal{R}(A)=\mathcal{L}(v,u)$ gde su $v=\begin{bmatrix}1&1&0&0\end{bmatrix}^T$ i $u=\begin{bmatrix}0&1&1&1\end{bmatrix}^T,$ a $\mathcal{N}(A)=\mathcal{L}(w)$ za $w=\begin{bmatrix}1&1&1\end{bmatrix}^T.$ Za pronađenu matricu $A$ odrediti bazu prostora vrsta i levog jezgra matrice $A.$

**Rešenje:**

Kao što smo videli u prethodnom zadatku, sve matrice koje imaju zadati prostor kolona dobijaju se formulom
$$A=\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}c_{00}&c_{01}&c_{02}\\c_{10}&c_{11}&c_{12}\end{bmatrix},$$
gde je matrica $C=\begin{bmatrix}c_{00}&c_{01}&c_{02}\\c_{10}&c_{11}&c_{12}\end{bmatrix}$ ranga $2.$

S obzirom da je $\mathcal{N}(A)=\mathcal{N}(C),$ potrebno je odrediti matricu $C$ tako da je $\mathcal{N}(C)=\mathcal{L}(w)\quad\Longleftrightarrow\quad \mathcal{N}(w)=\mathcal{R}(C^T).$ 

In [22]:
w=np.array([1,1,1.])
null_space(w[None,:])

array([[-0.57735027, -0.57735027],
       [ 0.78867513, -0.21132487],
       [-0.21132487,  0.78867513]])

In [23]:
C=null_space(w[None,:]).T
A=B@C
np.round(A,2)

array([[-0.58,  0.79, -0.21],
       [-1.15,  0.58,  0.58],
       [-0.58, -0.21,  0.79],
       [-0.58, -0.21,  0.79]])

Proverićemo postavljene uslove za matricu $A.$

In [24]:
np.linalg.matrix_rank(A) , np.linalg.matrix_rank(np.block([A,B]))

(2, 2)

In [25]:
w=np.array([1,1,1])
np.round(A@w,5)

array([0., 0., 0., 0.])

Možemo i samostalno da potražimo vrste matrice $C$ tako da je $\mathcal{N}(C)=\mathcal{L}(w).$ To znači da je rešenje homogenog sistema linearnih jednačina $Cx=\theta$ dato potprostorom 
$$\mathcal{L}(w)=\mathcal{L}\left(\begin{bmatrix}1&1&1\end{bmatrix}^T\right)
=\left\{\begin{bmatrix}x_0&x_1&x_2\end{bmatrix}^T\ \Big|\ x_0=x_1,\ x_0=x_2\right\}
=\left\{\begin{bmatrix}x_0&x_1&x_2\end{bmatrix}^T\ \Big|\ x_0-x_1=0,\ x_0-x_2=0\right\}.$$
Potprostor $\mathcal{L}(w)$ u potpunosti je opisan homogenim sistemom $\left\{\begin{array}{l}x_0-x_1=0,\\ x_0-x_2=0,\end{array}\right.$ pa je $C$ matrica ovog sistema, ili nekog njegovog ekvivalentnog oblika.

$\Longrightarrow\quad C=\begin{bmatrix}1&-1&0\\1&0&-1\end{bmatrix}.$ Matrica $A$ koja zadovoljava uslove $\mathcal{R}(A)=\mathcal{L}(v,u)$ i $\mathcal{N}(A)=\mathcal{L}(w)$ ima dekompoziciju punog ranga
$$A=BC=\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&-1&0\\1&0&-1\end{bmatrix},$$
i izračunata je narednim kodom.

In [26]:
C=np.array([[1, -1, 0],[1, 0, -1]])
A=B@C
print(A)

[[ 1 -1  0]
 [ 2 -1 -1]
 [ 1  0 -1]
 [ 1  0 -1]]


Proverićemo postavljene uslove za matricu $A.$

In [27]:
np.linalg.matrix_rank(A) , np.linalg.matrix_rank(np.block([A,B]))

(2, 2)

In [28]:
w=np.array([1,1,1])
A@w

array([0, 0, 0, 0])

Za određivanje baze prostora vrsta matrice $A$ možemo da iskoristimo poznavanje njene faktorizacije punog ranga,
$$A=BC=\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&-1&0\\1&0&-1\end{bmatrix}.$$
\begin{align}
\mathcal{R}(A^T)&=\mathcal{R}(C^T)=\mathcal{L}\left(\begin{bmatrix}1&-1&0\end{bmatrix}^T,\begin{bmatrix}1&0&-1\end{bmatrix}^T\right),
&&{\rm dim}(\mathcal{R}(A^T))={\rm rang}(A^T)={\rm rang}(A)=2,\\
\mathcal{N}(A^T)&=\mathcal{N}(B^T),&& B^T=\begin{bmatrix}1&1&0&0\\0&1&1&1\end{bmatrix}\sim\begin{bmatrix}1&0&-1&-1\\0&1&1&1\end{bmatrix}.
\end{align}

In [29]:
null_space(B.T)

array([[ 0.4472136,  0.4472136],
       [-0.4472136, -0.4472136],
       [ 0.7236068, -0.2763932],
       [-0.2763932,  0.7236068]])

Odgovarajući homogen sistem $B^Tx=\theta\Longleftrightarrow
\left[\begin{array}{cccc|c}1&0&-1&-1&0\\0&1&1&1&0\end{array}\right]$ ima rešenje
$$\left\{\begin{array}{l}x_0=x_2+x_3,\\ x_1=-x_2-x_3,\\ x_2,x_3\in\mathbb{R}\end{array}\right.\Longrightarrow\quad
x=\begin{bmatrix}x_2+x_3\\-x_2-x_3\\x_2\\x_3\end{bmatrix}
=x_2\begin{bmatrix}1\\-1\\1\\0\end{bmatrix}+x_3\begin{bmatrix}1\\-1\\0\\1\end{bmatrix},\ x_2,x_3\in\mathbb{R}
.$$

Zaključujemo da je
$$\mathcal{N}(A^T)=\mathcal{N}(B^T)=\mathcal{L}\left(\begin{bmatrix}1&-1&1&0\end{bmatrix}^T,\begin{bmatrix}1&-1&0&1\end{bmatrix}^T\right).$$
I u slučaju prostora vrsta i u slučaju levog jezgra pod linealom su zapisane baze ovih potprostora.

In [30]:
np.linalg.matrix_rank(np.block([A.T,C.T]))

2

In [31]:
L_Jezgro=np.array([[1,-1,1,0],[1,-1,0,1]])
np.round(L_Jezgro@A,5)

array([[0, 0, 0],
       [0, 0, 0]])

***

**Задатак 4.** Конструисати матрицу $A\in\mathcal{M}_{7\times6}$ чију базу простора колона чине прве три колоне матрице $B\in\mathcal{M}_{7\times6},$ а базу језгра чине последње три врсте матрице $B.$ Матрица $B$ се генерише наредном кодном ћелијом. Кодом се такође проверава да ли случајно дефинисана матрица има прве три линеарно независне колоне и последње три линеарно независне врсте како би се утврдила димензија одговарајућих фундаменталних потпростора. Разлог: да би конструкција била успешна мора да важи ${\rm rang}(A)+{\rm def}(A)=6.$ 

In [32]:
B=rndm.randn(7,6)-5*np.eye(7,6)
print(np.linalg.matrix_rank(B[:,:3]))
print(np.linalg.matrix_rank(B[-3:]))

3
3


**Решење :**

Матрица $A$ треба да се направи у облику производа пуног ранга $XY.$ Матрица $X$ описује простор колона матрице $A.$ То значи да $X$ треба да буде матрица типа $7\times3,$ где су њене три колоне преузете прве три колоне матрице $B.$

In [33]:
X=B[:,:3]

Матрица $Y$ је типа $3\times6$ и описује простор врста матрице $A.$ Језгро матрице $A$ је ортогонално на  простор врста $\mathcal{R}(A^T).$ Значи, последље три врсте матрице $B$ су ортогоналне на врсте $Y.$ Одредићемо их као језгро матрице са овим врстама,
$$\mathcal{N}(Y)=\mathcal{L}(B[-3:]^T)\quad\Longleftrightarrow\quad \mathcal{R}(Y^T)=(B[-3:]^T)^{\perp}
\quad\Longleftrightarrow\quad \mathcal{R}(Y^T)=\mathcal{N}(B[-3:]^T).$$

In [34]:
pom=B[-3:]
np.round(pom,2)

array([[-0.26, -1.47, -0.31,  0.14, -5.62, -0.4 ],
       [-0.49, -0.45,  0.8 , -1.08, -0.26, -4.12],
       [ 1.69, -0.31, -0.68, -1.32, -0.59, -0.96]])

In [35]:
Y=null_space(pom).T
np.round(Y,2)

array([[ 0.35, -0.38, -0.23,  0.78,  0.13, -0.26],
       [-0.48, -0.37, -0.75, -0.21,  0.16, -0.  ],
       [ 0.05, -0.81,  0.47, -0.23,  0.16,  0.22]])

In [36]:
A=X@Y
np.round(A,2)

array([[-1.46,  0.41,  1.57, -3.65, -0.32,  1.42],
       [ 2.01,  1.86,  3.3 ,  0.73, -0.74,  0.05],
       [-0.19,  4.5 , -3.03,  1.69, -0.85, -1.45],
       [-1.36, -0.76, -1.44, -1.14,  0.29,  0.25],
       [ 0.6 ,  0.89,  1.02,  0.18, -0.31, -0.  ],
       [ 0.08, -0.29,  0.83, -0.47, -0.01,  0.3 ],
       [ 0.71,  0.02, -0.47,  1.53,  0.07, -0.58]])

Проверимо сада простор колона и језгро добијене матрице $A.$

In [37]:
np.linalg.matrix_rank(np.block([X,A]))

3

In [38]:
np.round(A@pom.T,2)

array([[-0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [-0., -0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0., -0.],
       [ 0., -0.,  0.]])

***

**Задатак 5.** Описати језгра следећих матрица $A=\begin{bmatrix}1&2\\3&8\end{bmatrix},$ $B=\begin{bmatrix}A\\2A\end{bmatrix}$ и
$C=\begin{bmatrix}A&2A\end{bmatrix}.$

**Решење :**

С обзиром да је ${\rm det}(A)=2\neq0$ матрица $A$ је регуларна и $\mathcal{N}(A)=\{\theta\},$
$$Av=\theta\quad\Longleftrightarrow\quad v=A^{-1}\theta=\theta.$$

In [39]:
A1=np.array([[1,2],[3,8]])
np.linalg.matrix_rank(A1)

2

$B=\begin{bmatrix}A\\2A\end{bmatrix}=\begin{bmatrix}I\\2I\end{bmatrix}A.$ С обзиром да је ${\rm rang}\left(\begin{bmatrix}I\\2I\end{bmatrix}\right)=2$ i ${\rm rang}(A)=2,$ матрица $B$ је дата декомпозицијом пуног ранга. Одатле је $\mathcal{N}(B)=\mathcal{N}(A)=\{\theta\}.$ То можемо да проверимо и израчунавањем.

In [40]:
B=np.block([[A1],[2*A1]])
null_space(B)

array([], shape=(2, 0), dtype=float64)

In [41]:
np.linalg.matrix_rank(B)

2

In [42]:
null_space(B)

array([], shape=(2, 0), dtype=float64)

$C=\begin{bmatrix}A&2A\end{bmatrix}=A\begin{bmatrix}I&2I\end{bmatrix},$ што је декомпозиција пуног ранга матрице $C.$ Због тога је $\mathcal{N}(C)=\mathcal{N}\left(\begin{bmatrix}I&2I\end{bmatrix}\right).$

In [43]:
C=np.block([A1,2*A1])
C

array([[ 1,  2,  2,  4],
       [ 3,  8,  6, 16]])

In [44]:
jezgro=null_space(C)
jezgro

array([[-0.8, -0.4],
       [ 0.4, -0.8],
       [ 0.4,  0.2],
       [-0.2,  0.4]])

In [45]:
I=np.eye(2,dtype=int)
M=np.block([I,2*I])
Mjezgro=null_space(M)
Mjezgro

array([[-0.89442719,  0.        ],
       [ 0.        , -0.89442719],
       [ 0.4472136 ,  0.        ],
       [ 0.        ,  0.4472136 ]])

In [46]:
np.round(C@jezgro,6)

array([[ 0.,  0.],
       [-0.,  0.]])

In [47]:
np.round(M@jezgro,6)

array([[ 0.,  0.],
       [-0., -0.]])

In [48]:
np.round(C@Mjezgro,6)

array([[0., 0.],
       [0., 0.]])

In [49]:
np.round(M@Mjezgro,6)

array([[0., 0.],
       [0., 0.]])

Опис заједничког језгра ових матрица можемо да добијемо кроз блок форму. Услов $\begin{bmatrix}I&2I\end{bmatrix}x=\theta$ запишемо користећи конформну поделу вектора $x$ за наведено множење.
\begin{align}
&x=\begin{bmatrix}v_0\\v_1\end{bmatrix},\qquad v_0,v_1\in\mathbb{R}^2,\\
\begin{bmatrix}I&2I\end{bmatrix}x=\theta\quad&\Longleftrightarrow\quad \begin{bmatrix}I&2I\end{bmatrix}\begin{bmatrix}v_0\\v_1\end{bmatrix}=\theta
\quad\Longleftrightarrow\quad v_0+2v_1=\theta\\
&\Longrightarrow\quad v_0=-2v_1,\quad v_1\in\mathbb{R}^2
\quad\Longleftrightarrow\quad x=\begin{bmatrix}-2v_1\\v_1\end{bmatrix},\quad v_1\in\mathbb{R}^2\\
&\Longleftrightarrow\quad \mathcal{N}\left(\begin{bmatrix}I&2I\end{bmatrix}\right)=
\mathcal{L}\left(\begin{bmatrix}-2\\0\\1\\0\end{bmatrix},\begin{bmatrix}0\\-2\\0\\1\end{bmatrix}\right).
\end{align}

In [50]:
jezgro=np.array([[-2,0.],[0,-2],[1,0],[0,1]])
np.round(C@jezgro,2)

array([[0., 0.],
       [0., 0.]])

***

## Тихе врсте и колоне

Dekompozicije matrica koje obrađujemo u okviru kursa imaju svoju redukovanu i punu varijantu. Redukovane varijante dekompozicije su zapravo dekompozicije punog ranga 
$$A=BC,\qquad B\in\mathcal{M}_{m\times r},\ C\in\mathcal{M}_{r\times n},\quad {\rm rang}(B)={\rm rang}(C)=r,$$
kod kojih se faktori $B$ i $C$ biraju da budu nekog unapred određenog tipa - trougaone matrice ili matrice sa ortonormiranim kolonama, odnosno vrstama. I jedan i drugi uslov obezbeđuju linearnu nezavisnost kolona $B$ i vrsta matrice $C.$ 
Puna varijanta dekompozicija opisana je u narednom primeru.

**Primer 3.** U zadatku 3. konstruisana je matrica $A=XY,$ gde su $X\in\mathcal{M}_{7\times3}$ i $Y\in\mathcal{M}_{3\times6}.$ Dopunićemo matricu $X$ proizvoljnim kolonama do dimenzije $7\times7.$ 

In [51]:
print(np.round(X,2))
X1=rndm.rand(7,7)
X1[:,:3]=X
np.round(X1,2)

[[-4.26  0.09  1.45]
 [-0.29 -4.4  -0.14]
 [ 0.49  0.2  -5.9 ]
 [-0.77  2.3   0.24]
 [-0.26 -1.47 -0.31]
 [-0.49 -0.45  0.8 ]
 [ 1.69 -0.31 -0.68]]


array([[-4.26,  0.09,  1.45,  0.97,  0.79,  0.31,  0.17],
       [-0.29, -4.4 , -0.14,  0.97,  0.26,  0.24,  0.03],
       [ 0.49,  0.2 , -5.9 ,  0.85,  0.36,  0.78,  0.03],
       [-0.77,  2.3 ,  0.24,  0.2 ,  0.01,  0.91,  0.99],
       [-0.26, -1.47, -0.31,  0.77,  0.26,  0.34,  0.21],
       [-0.49, -0.45,  0.8 ,  0.39,  0.97,  0.99,  0.5 ],
       [ 1.69, -0.31, -0.68,  0.37,  0.75,  0.71,  0.21]])

In [52]:
np.linalg.matrix_rank(X1)

7

Sa novim faktorom $X$ popravljamo dimenzije faktora $Y$ tako da ostane $A=XY$ i da proizvod bude definisan.

In [53]:
print(np.round(Y,2))
Y1=np.zeros((7,6))
Y1[:3]=Y
np.round(Y1,2)

[[ 0.35 -0.38 -0.23  0.78  0.13 -0.26]
 [-0.48 -0.37 -0.75 -0.21  0.16 -0.  ]
 [ 0.05 -0.81  0.47 -0.23  0.16  0.22]]


array([[ 0.35, -0.38, -0.23,  0.78,  0.13, -0.26],
       [-0.48, -0.37, -0.75, -0.21,  0.16, -0.  ],
       [ 0.05, -0.81,  0.47, -0.23,  0.16,  0.22],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [54]:
np.round(A-X1@Y1,6)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0., -0.,  0.]])

***

Kroz eksperiment primećujemo da dodate kolone matrici $X$ nemaju uticaj na sadržaj matrice $A$ zahvaljujući nula-vrstama matrice $Y.$ Uočeno može da se pokaže u opštem slučaju zahvaljujući predstavljanju množenja matrica preko spoljašnjih proizvoda vektora-kolona i vektora-vrsta.

**Zadatak 6.** Napisati matricu $A\in\mathcal{M}_{4\times3}$ u obliku proizvoda $A=BC,$ $B\in\mathcal{M}_{4\times4},\ C\in\mathcal{M}_{4\times3}$ tako da važi: $\mathcal{R}(A)=\mathcal{L}(v,u)$ gde su $v=\begin{bmatrix}1&1&0&0\end{bmatrix}^T$ i $u=\begin{bmatrix}0&1&1&1\end{bmatrix}^T,$ a $\mathcal{N}(A)=\mathcal{L}(w)$ za $w=\begin{bmatrix}1&1&1\end{bmatrix}^T.$ 

**Rešenje:** 

Krenimo od dobijene faktorizacije punog ranga matrice u zadatku 2, $A=BC=\begin{bmatrix}1&0\\1&1\\0&1\\0&1\end{bmatrix}\begin{bmatrix}1&-1&0\\1&0&-1\end{bmatrix}.$ Matricu $B$ možemo da dopunimo proizvoljnim kolonama do matrice $4\times4$ dokle god matricu $C$ dopunimo nula-vrstama. 
$$A=B'C'=\begin{bmatrix}1&0&\cdot&\cdot\\1&1&\cdot&\cdot\\0&1&\cdot&\cdot\\0&1&\cdot&\cdot\end{bmatrix}\begin{bmatrix}1&-1&0\\1&0&-1\\0&0&0\\0&0&0\end{bmatrix}.$$

Dopunjene kolone ne učestvuju u linearnim kombinacijama za formiranje matrice $A,$ tj. nemaju uticaj na vrednosti unutar matrice $A$ - tihe kolone matrice $B'.$ Da ove kolone zaista ne učestvuju u izrazu matrice $A$ možemo da uvidimo i na osnovu operacije spoljašnjeg proizvoda vektora.
\begin{align}
B'C'&=\begin{bmatrix}1&0&\cdot&\cdot\\1&1&\cdot&\cdot\\0&1&\cdot&\cdot\\0&1&\cdot&\cdot\end{bmatrix}\begin{bmatrix}1&-1&0\\1&0&-1\\0&0&0\\0&0&0\end{bmatrix}\\
&=\begin{bmatrix}1\\1\\0\\0\end{bmatrix}\begin{bmatrix}1&-1&0\end{bmatrix}+
\begin{bmatrix}0\\1\\1\\1\end{bmatrix}\begin{bmatrix}1&0&-1\end{bmatrix}+
\begin{bmatrix}\cdot\\\cdot\\\cdot\\\cdot\end{bmatrix}\begin{bmatrix}0&0&0\end{bmatrix}+
\begin{bmatrix}\cdot\\\cdot\\\cdot\\\cdot\end{bmatrix}\begin{bmatrix}0&0&0\end{bmatrix}\\
&=\begin{bmatrix}1\\1\\0\\0\end{bmatrix}\begin{bmatrix}1&-1&0\end{bmatrix}+
\begin{bmatrix}0\\1\\1\\1\end{bmatrix}\begin{bmatrix}1&0&-1\end{bmatrix}+O_{4\times3}+O_{4\times3}.
\end{align}

***

**Zadatak 7.** Neka za matricu $A\in\mathcal{M}_{m\times n}$ važi razlaganje $A=BC,$ $B\in\mathcal{M}_{m\times m},$ je regularna matrica i $C\in\mathcal{M}_{m\times n}$ je matrica ranga $r,$ a razlaganje prikazano u blok formi glasi: 
$$A=BC=\left[\begin{array}{c|c} B_{m\times r}&B_{m\times(m-r)}\end{array}\right]\left[\begin{array}{c} C_{r\times n}\\\hline O_{(m-r)\times n}\end{array}\right].$$
Pokazati da je $\mathcal{R}(A)=\mathcal{R}(B_{m\times r})$ i $\mathcal{N}(A)=\mathcal{N}(C_{r\times n}).$

**Rešenje:**

Dovoljno je da pokažemo da je $A=B_{m\times r}C_{r\times n}$ dekompozicija punog ranga matrice $A.$ Za početak, pokažimo da ova jednakost važi. Operacija spoljašnjeg proizvoda vektora se prirodno uopštava na blok matrice, tj. važi
$$A=BC=\left[\begin{array}{c|c} B_{m\times r}&B_{m\times(m-r)}\end{array}\right]\left[\begin{array}{c} C_{r\times n}\\\hline O_{(m-r)\times n}\end{array}\right]=B_{m\times r}C_{r\times n}+B_{m\times(m-r)}O_{(m-r)\times n}
=B_{m\times r}C_{r\times n}.$$ 

Ostaje još da pokažemo da su matrice $B_{m\times r}$ i $C_{r\times n}$ ranga $r.$ 

Matrica $B$ je regularna pa je njen skup kolona linearno nezavisan. Zbog toga je i svaki podskup kolona takođe linearno nezavisan. Zaključujemo da su kolone bloka $B_{m\times r}$ linearno nezavisne, tj. ${\rm rang}(B_{m\times r})=r.$ 

Matrica $C$ je ranga $r,$ pa ima $r$ linearno nezavisnih vrsta. Jedine nenula vrste matrice $C$ nalaze se u bloku $C_{r\times n},$ te on sadrži sve linearno nezavisne vrste matrice $C.$ Zbog toga je ${\rm rang}(C_{r\times n})=r.$

***

<div class="alert alert-block alert-info">
Zbog toga što kolone bloka $B_{m\times(m-r)}$ ne utiču na vrednosti unutar matrice $A$ zovemo ih <b>tihe kolone</b> razlaganja $A=BC.$ Zadatkom 7 uspostavljena je veza između razlaganja u blok formi 
$$A=BC=\left[\begin{array}{c|c} B_{m\times r}&B_{m\times(m-r)}\end{array}\right]\left[\begin{array}{c} C_{r\times n}\\\hline O_{(m-r)\times n}\end{array}\right]$$    
i dekompozicije punog ranga matrice $A=B_{m\times r}C_{r\times n}.$ Primetimo da se i svaka dekompozicija punog ranga lako dovodi na dato blok razlaganje. Ovaj prelazak podrazumeva pravljenje dopune kolona bloka $B_{m\times r}$ do baze prostora $\mathbb{R}^m,$ a za matricu $C$ potrebno je izvršiti dopunu bloka $C_{r\times n}$ nula-vrstama do odgovarajuće dimenzije.
    </div>

Postojanje dekompozicije $A=BC,$ $B\in\mathcal{M}_{m\times m},$ regularna matrica i $C\in\mathcal{M}_{m\times n}$ matrica ranga $r,$ bitno je jer se iz njega mogu dobiti informacije o fundamentalnim potprostorima matrice $A.$ Za sada je poznato da je $\mathcal{R}(A)=\mathcal{R}(B_{m\times r})$ i $\mathcal{N}(A)=\mathcal{N}(C_{r\times n}).$ Regularnost matrice $B$ znači postojanje njene inverzne matrice $T=B^{-1}.$ Tada važi $TA=C.$

**Zadatak 7.** Neka za matricu $A\in\mathcal{M}_{m\times n}$ važi $TA=C,$ $T\in\mathcal{M}_{m\times m},$ je regularna matrica i $C\in\mathcal{M}_{m\times n}$ je matrica ranga $r,$ a proizvod u blok formi glasi: 
$$\left[\begin{array}{c} T_{r\times m}\\\hline T_{(m-r)\times m}\end{array}\right]A=C=\left[\begin{array}{c} C_{r\times n}\\\hline O_{(m-r)\times n}\end{array}\right].$$
Pokazati da je $\mathcal{N}(A^T)=\mathcal{R}\big(T_{(m-r)\times m}^T\big).$

**Rešenje:**

S obzirom da je ${\rm rang}(A)=r$ to je ${\rm def}(A^T)=m-r={\rm rang}(T_{(m-r)\times m}^T).$ Blok množenje matrica potvrđuje da je
$$T_{(m-r)\times m}A=O_{(m-r)\times n}\quad\Longleftrightarrow\quad AT_{(m-r)\times m}^T=O_{(m-r)\times m}^T,$$
pa vrste bloka $T_{(m-r)\times m}$ zaista predstavljaju bazu prostora levog jezgra matrice $A.$

***

**Primer 4.** Slično primeru 3, u proizvodu $A=BC$ ukoliko matrica $B$ sadrži nula-kolone matricu $C$ možemo da dopunimo proizvoljnim vrstama a da rezultat množenja ne bude promenjen.
$$B=\left[\begin{array}{c|c|c|c|c|c}\phantom{W}&\phantom{W}&\phantom{W}&\phantom{W}\\
v_0&\dots&v_{r-1}&\theta&\dots&\theta\\\phantom{W}&\phantom{W}&\phantom{W}&\phantom{W}\end{array}\right]\in\mathcal{M}_{m\times n},\qquad 
C=\left[\begin{array}{c}\phantom{W}u_0^T\phantom{W}\\\hline\vdots\\\hline
\phantom{W}u_{r-1}^T\phantom{W}\\\hline u_r^T\\\hline\vdots\\\hline u_{m-1}^T\end{array}\right]\in\mathcal{M}_{n\times n}.$$

U tom slučaju su vrste $u_r,\dots,u_{m-1}$ **tihe vrste** dekompozicije jer njihov sadržaj ne utiče na rezultat proizvoda.

In [55]:
print(np.round(X,2))
X2=np.zeros((7,6))
X2[:,:3]=X
np.round(X2,2)

[[-4.26  0.09  1.45]
 [-0.29 -4.4  -0.14]
 [ 0.49  0.2  -5.9 ]
 [-0.77  2.3   0.24]
 [-0.26 -1.47 -0.31]
 [-0.49 -0.45  0.8 ]
 [ 1.69 -0.31 -0.68]]


array([[-4.26,  0.09,  1.45,  0.  ,  0.  ,  0.  ],
       [-0.29, -4.4 , -0.14,  0.  ,  0.  ,  0.  ],
       [ 0.49,  0.2 , -5.9 ,  0.  ,  0.  ,  0.  ],
       [-0.77,  2.3 ,  0.24,  0.  ,  0.  ,  0.  ],
       [-0.26, -1.47, -0.31,  0.  ,  0.  ,  0.  ],
       [-0.49, -0.45,  0.8 ,  0.  ,  0.  ,  0.  ],
       [ 1.69, -0.31, -0.68,  0.  ,  0.  ,  0.  ]])

In [56]:
print(np.round(Y,2))
Y2=rndm.rand(6,6)
Y2[:3]=Y
np.round(Y2,2)

[[ 0.35 -0.38 -0.23  0.78  0.13 -0.26]
 [-0.48 -0.37 -0.75 -0.21  0.16 -0.  ]
 [ 0.05 -0.81  0.47 -0.23  0.16  0.22]]


array([[ 0.35, -0.38, -0.23,  0.78,  0.13, -0.26],
       [-0.48, -0.37, -0.75, -0.21,  0.16, -0.  ],
       [ 0.05, -0.81,  0.47, -0.23,  0.16,  0.22],
       [ 0.68,  0.24,  0.34,  0.61,  0.44,  0.14],
       [ 0.15,  0.93,  0.52,  0.78,  0.93,  0.54],
       [ 0.24,  0.63,  0.6 ,  0.77,  0.91,  0.45]])

In [57]:
np.linalg.matrix_rank(Y2)

6

In [58]:
np.round(A-X2@Y2,6)

array([[ 0., -0.,  0.,  0.,  0., -0.],
       [ 0.,  0., -0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -0.],
       [-0.,  0.,  0.,  0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0., -0.,  0.]])

***

<div class="alert alert-block alert-info">
Dekompozicija punog ranga matrice $A\in\mathcal{M}_{m\times n},$ $A=B_{m\times r}C_{r\times n},$ može i na drugi način da se proširi do proizvoda sa regularnom matricom. Neka su $B''\in\mathcal{M}_{m\times n}$ matrica u stepenastoj formi kolona, a $C''\in\mathcal{M}_{n\times n}$ regularna matrica, tada proizvod $A=B''C'',$  u blok formi
$$A=B''C''=\left[\begin{array}{c|c} B_{m\times r}&O_{m\times(n-r)}\end{array}\right]\left[\begin{array}{c} C_{r\times n}\\\hline C_{(n-r)\times n}\end{array}\right]$$
    predstavlja proširenje dekompozicije punog ranga koje otkriva jezgro matrice $A.$
Ukoliko označimo $S=C^{-1},$ važi $AS=B.$ Uz konformnu blokovsku podelu   
    $$AS=A\left[\begin{array}{c|c} S_{n\times r}&S_{n\times(n-r)}\end{array}\right]=\left[\begin{array}{c|c} B_{m\times r}&O_{m\times(n-r)}\end{array}\right],$$
kolone bloka $S_{(n-r)\times n}$ razapinju jezgro matrice $A.$    
    </div>

**Primer 5.** Još jedan način opisivanja tihih vrsta i kolona je kroz ubacivanje dijagonalnog faktora $D,$
$$A=BDC,\qquad B\in\mathcal{M}_{m\times m},\ D\in\mathcal{M}_{m\times n},\ C\in\mathcal{M}_{n\times n},$$
$$B=\left[\begin{array}{c|c|c|c}\phantom{W}&\phantom{W}&\phantom{W}&\phantom{W}\\
v_0&v_1&\dots&v_{m-1}\\\phantom{W}&\phantom{W}&\phantom{W}&\phantom{W}\end{array}\right]\in\mathcal{M}_{m\times m},\qquad 
D=\begin{bmatrix}d_0&0&\dots&0&0&\dots&0\\0&d_1&\dots&0&0&\dots&0\\
\vdots&\vdots&&\vdots&\vdots&&\vdots\\0&0&\dots&d_{r-1}&0&\dots&0\\
0&0&\dots&0&0&\dots&0\\\vdots&\vdots&&\vdots&\vdots&&\vdots\\
0&0&\dots&0&0&\dots&0\end{bmatrix}\in\mathcal{M}_{m\times n},\qquad
C=\left[\begin{array}{c}\phantom{W}u_0^T\phantom{W}\\\hline
\phantom{W}u_{1}^T\phantom{W}\\\hline\vdots\\\hline u_{n-1}^T\end{array}\right]\in\mathcal{M}_{n\times n}.$$

Primetimo da $A=BDC=(BD)C$ označava skaliranje kolona matrice $B$ odgovarajućim dijagonalnim elementima matrice $D,$ kojim se proizvod $A=BDC$ svodi na proizvode matrica iz primera $4.$  Slično, $A=B(DC)$ opisuje skaliranje vrsta matrice $C$ dijagonalnim elementima matrice $D,$ nakon čega proizvod $A=BDC$ tumačimo kao dekompoziciju iz primera $3.$

Na osnovu pravila za množenje preko spoljašnjeg proizvoda je
$$A=BDC=d_0\,v_0u_0^T+d_1\,v_1u_1^T+\dots+d_{r-1}\,v_{r-1}u_{r-1}^T+0\,v_ru_r^T+\dots
=d_0\,v_0u_0^T+d_1\,v_1u_1^T+\dots+d_{r-1}\,v_{r-1}u_{r-1}^T.$$

Primećujemo da dužina dijagonale matrice $D,$ tačnije njenih nenula elemenata, određuje bitne kolone matrice $B$ i vrste matrice $C.$ Preostale kolone i vrste ovih matrica predstavljaju njihove tihe delove.

In [59]:
D=np.zeros((7,6))
D[:3,:3]=np.eye(3)
print(D)
np.round(A-X1@D@Y2,6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


array([[ 0., -0.,  0.,  0.,  0., -0.],
       [ 0.,  0., -0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -0.],
       [-0.,  0.,  0.,  0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0., -0.,  0.]])

***

Napomenimo da je veoma važno pratiti rang i defekt matrica kojima se radi prilikom izračunavanja u konačnoj preciznosti s obzirom na netačnosti koje ovo okruženje neminovno nosi.

**Primer 6.** Matrica $A$ koja se kreira narednim kodom je ranga $2.$

In [60]:
B=rndm.normal(-1,2,(25,5))
B=B@np.array([[1,0,1,-1,2],[0,1,1,1,-1],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])
A=B.T@B
print(B.shape)
print(A.shape)
np.round(A,2)

(25, 5)
(5, 5)


array([[ 9.1410e+01,  3.2000e-01,  9.1740e+01, -9.1090e+01,  1.8250e+02],
       [ 3.2000e-01,  1.4080e+02,  1.4113e+02,  1.4048e+02, -1.4015e+02],
       [ 9.1740e+01,  1.4113e+02,  2.3286e+02,  4.9390e+01,  4.2350e+01],
       [-9.1090e+01,  1.4048e+02,  4.9390e+01,  2.3157e+02, -3.2265e+02],
       [ 1.8250e+02, -1.4015e+02,  4.2350e+01, -3.2265e+02,  5.0515e+02]])

In [61]:
np.linalg.matrix_rank(A)

2

Matrica $C$ u nastavku je regularna matrica.

In [62]:
C=rndm.rand(5,5)
C=np.tril(C)+(np.tril(C)).T+5*np.eye(5,5)
np.round(C,2)

array([[6.97, 0.63, 0.27, 0.8 , 0.05],
       [0.63, 5.5 , 0.23, 0.18, 0.11],
       [0.27, 0.23, 6.78, 0.17, 0.23],
       [0.8 , 0.18, 0.17, 5.3 , 0.63],
       [0.05, 0.11, 0.23, 0.63, 5.48]])

In [63]:
np.linalg.matrix_rank(C)

5

U proizvodu $A^TCA$ kreirana je simetrična matrica ranga $2,$ tj. singularna matrica. Ipak, u postupku izračunavanja inverzne matrice Python to nije prepoznao.

In [64]:
M=A.T@C@A
np.linalg.inv(M)

array([[-2.84206366e+10, -3.92587246e+10,  3.29169435e+10,
         8.18725528e+09,  1.84547416e+09],
       [-1.06946245e+10, -1.28335494e+10,  1.49724743e+10,
        -8.55569959e+09, -6.41677469e+09],
       [ 2.14348956e+10,  2.22859009e+10, -2.31369062e+10,
         3.40402117e+09,  2.55301588e+09],
       [-1.44948014e+10, -1.93187941e+09,  6.54882661e+09,
        -1.28791961e+09,  3.32902759e+09],
       [-3.75453024e+09,  7.52047214e+09, -1.61560534e+09,
        -6.43959803e+09, -5.34731224e+08]])

In [65]:
np.linalg.matrix_rank(M)

2

Trebalo bi da se u slučaju singularne matrice dobije poruka o tome prilikom poziva funkcije `linalg.inv`.

In [66]:
X=np.array([[1,0,0],[0,1,0],[0,0,0]])
np.linalg.inv(X)

LinAlgError: Singular matrix

***