# QR dekompozicija

**Sadržaj:**
1. [Gram-Šmitov algoritam kao faktorizacija matrica](#Gram-Šmitov-algoritam-kao-faktorizacija-matrica)
1. [Modifikovan Gram-Šmitov postupak ortonormalizacije](#Modifikovan-Gram-Šmitov-postupak-ortonormalizacije)
1. [Python ugrađene funkcije](#Python-ugrađene-funkcije)
1. [Izbor pivot elementa](#Izbor-pivot-elementa)

In [1]:
import numpy as np
import numpy.random as rndm
from timeit import default_timer as timer

***

## Gram-Šmitov algoritam kao faktorizacija matrica

QR dekompozicija matrice $A$ predstavlja postupak razlaganje matrice $A$ u proizvod jedne matrice sa ortonormiranim kolonama $(Q)$ i jedne trougaone matrice $(R).$ Puna QR dekompozicija je rastavljanje matrice $A$ u proizvod ortogonalne $Q$ i trougaone matrice $R.$ 

Jedan od postupaka dobijanja redukovane QR faktorizacije omogućava Gram-Šmitov algoritam.

Polazeći od skupa vektora $v_0,v_1,\dots,v_{n-1},$ Gram-Šmitov algoritam u svakom koraku generiše jedan nov vektor $u_i$ ortogonalan na prethodno generisane vektore $u_0,u_1,\dots,u_{i-1}.$ Kada je polazni skup vektora $v_0,v_1,\dots,v_{n-1}$ linearno nezavisan, Gram-Šmitov algoritam vraća $n$ ortogonalnih vektora $u_0,u_1,\dots,u_{n-1}.$ Ukoliko polazni skup vektora nije linearno nezavisan, tada Gram-Šmitov algoritam vraća $r$ orotogonalnih vektora gde je $r$ maksimalan broj linearno nezavisnih vektora u skupu $v_0,v_1,\dots,v_{n-1},$ tj. $$r=\dim\left(\mathcal{L}(v_0,v_1,\dots,v_{n-1})\right).$$ Normiranjem skupa ortogonalnih vektora $u_0,u_1,\dots,u_{r-1}$ dobijamo ortonormiran skup $q_0,q_1,\dots,q_{r-1}.$ U nastavku, pod Gram-Šmitovim postupkom podrazumevaćemo proces ortonormiranja skupa ulaznih vektora,
$$v_0,v_1,\dots,v_{n-1}\quad\mapsto\quad q_0,q_1,\dots,q_{r-1}.$$

Predstavićemo strukturu Gram-Šmitovog postupka za ortonormiranje linearno nezavisnog skupa vektora

> 1. korak: 
\begin{align}
&u_0=v_0,\\
&q_0=\dfrac{u_0}{\|u_0\|}
\end{align}
> $\{v_0\}^{\perp}=\{u_0\}^{\perp}=\{q_0\}^{\perp}$

> 2. korak: 
\begin{align}
&u_1=\left(I-q_0q_0^T\right)v_1,\\
&q_1=\dfrac{u_1}{\|u_1\|}
\end{align}
> $\{v_0,v_1\}^{\perp}=\{u_0,u_1\}^{\perp}=\{q_0,q_1\}^{\perp}$|

> 3. korak: 
\begin{align}
&u_2=(I-q_0q_0^T-q_1q_1^T)v_2,\\
&q_2=\dfrac{u_2}{\|u_2\|}
\end{align}
> $\{v_0,v_1,v_2\}^{\perp}=\{u_0,u_1,u_2\}^{\perp}=\{q_0,q_1,q_2\}^{\perp}$|

$\vdots$

> n. korak: 
\begin{align}
&u_{n-1}=(I-q_0q_0^T-q_1q_1^T-\dots-q_{n-2}q_{n-2}^T)v_{n-1},\\
&q_{n-1}=\dfrac{u_{n-1}}{\|u_{n-1}\|}
\end{align}
> $\{v_0,v_1,\dots,v_{n-1}\}^{\perp}=\{u_0,u_1,\dots,u_{n-1}\}^{\perp}=\{q_0,q_1,\dots,q_{n-1}\}^{\perp}$

***

Veoma važno svojstvo Gram-Šmitovog algoritma  jeste očuvanje potprostora generisanih ulaznim vektorima:
\begin{align}
 	\mathcal{L}(v_0)&=\mathcal{L}(q_0),\\
 	\mathcal{L}(v_0,v_1)&=\mathcal{L}(q_0,q_1),\\
 	\mathcal{L}(v_0,v_1,v_2)&=\mathcal{L}(q_0,q_1,q_2),\\
 	&\ \vdots\\
 	\mathcal{L}(v_0,v_1,\dots,v_{n-1})&=\mathcal{L}(q_0,q_1,\dots,q_{n-1}),
\end{align}
 tj. u skraćenoj formi
$$\mathcal{L}(v_0,\dots,v_k)=\mathcal{L}(q_0,\dots,q_k),\ \forall k\in(n).$$

To se najbolje uočava iz skalarnog oblika jednog koraka Gram-Šmitovog algoritma.
Ortogonalni vektor $u_k$ dobija se u obliku
$$u_k=\|u_k\|q_k=v_k-\lambda_0q_0-\lambda_1q_1-\dots-\lambda_{k-1}q_{k-1}\in\mathcal{L}(q_0,q_1,\dots,q_{k-1},v_k).$$
Zbog toga je 
$$v_k=\lambda_0q_0+\lambda_1q_1+\dots+\lambda_{k-1}q_{k-1}+\|u_k\|q_k\in\mathcal{L}(q_0,q_1,\dots,q_k).$$ 
Kako ovo važi za svaki vektor $v_k$ zaključujemo da su jednakosti o potprostorima tačne. 

Kada je $A$ regularna realna matrica dimenzije $n,$ 
$$A=\left[\begin{array}{c|c|c|c}
\!\!\begin{array}{c}\phantom{i}\\a_0\\\phantom{i}\end{array}\!\!
&\,a_1\,&\dots&a_{n-1}\end{array}\right],$$
njene kolone $a_0,a_1,\dots,a_{n-1}$  predstavljaju bazu  prostora $\mathbb{R}^n.$ Gram-Šmitovim postupkom  bazu sastavljenu od vektora kolona $\{a_0,a_1,\dots,a_{n-1}\}$ prevodimo u ortonormiranu bazu $\{q_0,q_1,\dots,q_{n-1}\}$ prostora $\mathbb{R}^n.$ Matrica $Q$ sa kolonama $q_0,q_1,\dots,q_{n-1}$ jeste ortogonalna matrica, tj. važi  $Q^TQ=QQ^T=I.$	

Svaki vektor-kolona $a_i$ se Furijeovim koordinatama može predstaviti preko vektora $q_0,q_1,\dots,q_i.$
$$\begin{array}{r@{}l@{}l@{}l}
	a_0&=(q_0^Ta_0)q_0&,&\\[4pt]
	a_1&=(q_0^Ta_1)q_0&+(q_1^Ta_1)q_1&,\\
	&\vdots&&\\
	a_{n-1}&=(q_0^Ta_{n-1})q_0&+(q_1^Ta_{n-1})q_1&+\dots+(q_{n-1}^Ta_{n-1})q_{n-1}.
\end{array}$$	

U matričnom obliku gornje jednakosti glase
$$
\left[\begin{array}{c|c|c|c}
	\!\!\begin{array}{c}\phantom{i}\\a_0\\\phantom{i}\end{array}\!\!
	&\,a_1\,&\dots&a_{n-1} \end{array}\right]=\left[\begin{array}{c|c|c|c}
	\!\!\begin{array}{c}\phantom{i}\\q_0\\\phantom{i}\end{array}\!\!
	&\,q_1\,&\dots&q_{n-1} \end{array}\right]
\begin{bmatrix} q_0^Ta_0&q_0^Ta_1&\dots&q_0^Ta_{n-1}\\
	0&q_1^Ta_1&\dots&q_1^Ta_{n-1}\\
	\vdots&\vdots&\ddots&\vdots\\
	0&0&\dots&q_{n-1}^Ta_{n-1}\end{bmatrix}$$
	$$\Longleftrightarrow\ A=QR.$$
Zaključujemo da se svaka regularna matrica može predstaviti kao proizvod jedne ortogonalne i jedne gornje trougaone matrice sa pozitivnim dijagonalnim elementima. Primetimo da su kolone matrice $Q$ i Furijeove koordinate iz matrice $R$ produkti Gram-Šmitovog algoritma. U postupku izračunavanja kolona $q_i$ izračunavaju se i Furijeove koordinate.  

Gram-Šmitov postupak gradi faktore $Q$ i $R$ kolonu-po-kolonu.  Neka su delovi faktora $Q$ i $R$ dobijeni u $k$ koraka označeni sa $Q_{k}\in\mathcal{M}_{n\times k}$ i $R_{k}\in\mathcal{M}_{n\times k}.$
$$R_{k}=\begin{bmatrix} r_{00}&r_{01}&\dots&r_{0\,k-1} \\
0&r_{11}&\dots&r_{1\,k-1}\\
\vdots&\vdots&\ddots&\vdots\\ 
0&0&\dots&r_{k-1\,k-1}\\
0&0&\dots&0\\\vdots&\vdots&&\vdots\\
0&0&\dots&0\end{bmatrix}
,\qquad
Q_{k}=\left[\begin{array}{c|c|c|c}
\!\!\begin{array}{c}\phantom{i}\\q_0\\\phantom{i}\end{array}\!\!
&\,q_1\,&\dots&q_{k-1} \end{array}\right].
$$
Svaki korak Gram-Šmitovog algoritma vrši transformacije sledećeg tipa:
$$R_1\to R_2\to\dots\to R_{n}=R,\qquad\qquad
Q_1\to Q_2\to\dots\to Q_{n}=Q.$$
Prelazak $Q_{k}\to Q_{k+1}$ i $R_{k}\to R_{k+1}$ označava dodavanje nove kolone prethodnoj matrici. Takvu realizaciju algoritma zovemo **izgradnja po kolonama**.

$(k+1)-$vi korak može da se prikaže i matričnim operacijama koje vektorizuju izračunavanja
$$\left\{\begin{array}{r@{}l}
u_{k}&=a_{k}-Q_{k}(Q_{k}^Ta_{k}),\\[6pt] 
q_{k}&=\dfrac{u_{k}}{\|u_{k}\|}\,.
\end{array}\right.$$
Odatle je 
$$a_k=Q_{k}(Q_{k}^Ta_k)+u_k=Q_{k}(Q_{k}^Ta_k)+\|u_k\|q_k.$$

Izgradnja matrica $Q_{k+1}$ i $R_{k+1}$ je tada
$$
R_{k+1}=\left[\begin{array}{c|c}
\phantom{i}&\phantom{i}\\
 \phantom{i} & Q_{k}^Ta_k\\
R_{k} &\phantom{i}\\
\phantom{i}     & \|u_k\|\\[4pt]
\phantom{i}     & \theta
\end{array}
\right],\qquad
Q_{k+1}=\left[\begin{array}{c|c}
\phantom{i}&\phantom{i}\\
Q_{k}&q_k\\
\phantom{i}&\phantom{i}
\end{array}\right],\quad k\in(n).
$$
Dijagonalni elementi matrica $R_k$ su norme ortogonalnih vektora $u_i,\ i\in(k)$ pa predstavljaju pozitivne vrednosti.

Operacijska složenost ovog algoritma je $\mathcal{O}(2n^3)$

***

Furijeove koordinate u matrici $R$ sugerišu još jedan način realizacije Gram-Šmitovog algoritma: **izgradnja po vrsti** matrice $R,$ ili **modifikovani Gram-Šmit**. Prva vrsta matrice $R$ iznosi $q_0^TA$ i zavisi isključivo od vektora $q_0.$ Slično, drugu vrstu matrice $R$ čine Furijeove koordinate kolona matrice $A$ u odnosu na vektor $q_1,\ q_1^TA,$ itd. Drugim rečhima, sa svakim korakom koji proizvede nov vektor $q_k$ gradimo novu vrstu matrice $R,$ umesto nove kolone. Ovo je naročito korisno kod matrica velikih dimenzija. Naime, pojedinačni korak kada se izvodi direktnim sumiranjem ima veliku akumulaciju grešaka zaokruživanja. Umesto toga, popunjavanjem vrsta matrice $R,$ korak izračunavanje  se realizuje kroz niz od $k-1$ međurezultata: 
$$\begin{array}{c@{}c@{}c@{}l}
	u_{k0}&=&a_{k}&-(q_0\cdot a_k)q_0,\\[4pt]
	u_{k1}&=&u_{k0}&-(q_1\cdot u_{k0})q_1,\\
	&&\vdots&\\
	u_{k\,i}&=&u_{k\,i-1}&-(q_{i}\cdot u_{k\,i-1})q_{i},\\
	&&\vdots&\\
	u_{k\,k-1}&=&u_{k\,k-2}&-(q_{k-1}\cdot u_{k\,k-1})q_{k-1},\\[4pt]
	u_k&=&u_{k\,k-1}&.
\end{array}$$

Novi ortogonalni vektor $k-$te iteracije modifikovanog Gram-Šmitovog postupka je poslednji rezultat niza: $u_k=u_{k\,k-1}.$ Njegovim normiranjem dobija se novi ortonormirani vektor $q_k.$

***

## Modifikovan Gram-Šmitov postupak ortonormalizacije

Ulaz algoritma su vektori $a_0,a_1,\dots,a_{n-1},$ smešteni u kolone matrice $A\in\mathcal{M}_{m\times n},$
 $$A=\left[\begin{array}{c|c|c|c}
\begin{array}{c}\phantom{i}\\a_0\\\phantom{i}\end{array}
&\,a_1\,&\dots&a_{n-1} \end{array}\right].$$
Pretpostavićemo da su vektori linearno nezavisni.

- Nakon izračunavanja vektora $q_0=\dfrac{a_0}{\|a_0\|},\ a_0\neq\theta,$ i za sve vektore $a_1,\dots,a_{n-1}$ određuju se  Furijeove koordinate i vektori $u_{k0}:$
$$q_0^Ta_k,\qquad u_{k0}=a_k-(q_0^Ta_k)q_0,\qquad k=1,\dots,n-1.$$
Na taj način dobijeni su prva kolona matrice $Q$ i prva vrsta matrice $R:$
$$Q_1=\begin{bmatrix}\phantom{W}\\q_0\\\phantom{W}\end{bmatrix},\qquad 
R_1=\begin{bmatrix}\|u_0\|&q_0^Ta_1&\dots&q_0^Ta_{n-1}\end{bmatrix}.$$

- Vektor $u_1=u_{10}$ je dobijen u prethodnom koraku. Njegovim normiranjem dobijamo $q_1.$

- Nakon izračunavanja vektora $q_1,$ za sve vektore $a_2,\dots,a_{n-1}$ izračunati  Furijeove koordinate i vektore $u_{k1}:$
$$q_1^Ta_k=q_1^Tu_{k0},\quad u_{k1}=u_{k0}-(q_1^Tu_{k0})q_1,\quad k=2,\dots,n-1.$$
Na taj način dobijeni su druga kolona matrice $Q$ i druga vrsta matrice $R:$
$$Q_2=\left[\begin{array}{c|c}\phantom{W}&\phantom{W}\\q_0&q_1\\\phantom{W}&\phantom{W}\end{array}\right],\qquad 
R_2=\begin{bmatrix}\|u_0\|&q_0^Ta_1&q_0^Ta_2&\dots&q_0^Ta_{n-1}\\
0&\|u_1\|&q_1^Ta_2&\dots&q_1^Ta_{n-1}\end{bmatrix}.$$

- Vektor $u_2=u_{21}$ je dobijen u prethodnom koraku. Njegovim normiranjem dobijamo $q_2.$

- Nakon izračunavanja vektora $q_2,$ za sve vektore $a_3,\dots,a_{n-1}$ izračunati  Furijeove koordinate i vektore $u_{k2}:$
$$q_2^Ta_k=q_2^Tu_{k1},\quad u_{k2}=u_{k1}-(q_2^Tu_{k1})q_2,\quad k=3,\dots,n-1.$$
Na taj način dobijeni su druga kolona matrice $Q$ i druga vrsta matrice $R:$
$$Q_3=\left[\begin{array}{c|c|c}\phantom{W}&\phantom{W}&\phantom{W}\\
q_0&q_1&q_3\\
\phantom{W}&\phantom{W}&\phantom{W}\end{array}\right],\qquad 
R_3=\begin{bmatrix}\|u_0\|&q_0^Ta_1&q_0^Ta_2&\dots&q_0^Ta_{n-1}\\
0&\|u_1\|&q_1^Ta_2&\dots&q_1^Ta_{n-1}\\
0&0&\|u_2\|&\dots&q_2^Ta_{n-1}
\end{bmatrix}.$$

- $\vdots$

- Vektor $u_{n-1}=u_{n-1\,n-2}$ je dobijen u prethodnom koraku. Njegovim normiranjem dobijamo $q_{n-1}.$ 

***

## Python ugrađene funkcije

Ugrađena funkcija Pythona za izračunavanje QR faktorizacije je `np.linalg.qr`. Upoznaćemo je na primeru matrice koja nije punog ranga.

**Primer 1.** Primenimo ugrađene funkcije na regularnu matricu $A=\begin{bmatrix}1&-1&1\\0&0&2\\
	1&2&0\end{bmatrix}$ i na jednu singularnu matricu. Koristeći trougaonu dekompoziciju kreiraćemo matricu $B$ ranga $3$  za primenu ugrađenih funkcija QR faktorizacije.

In [2]:
A=np.array([[1,-1,1.],[0,0,2],[1,2,0]])
np.linalg.matrix_rank(A)

3

In [3]:
Q,R=np.linalg.qr(A,mode='reduced')  #direktiva za redukovanu QR
print(np.round(Q,6))
print(np.round(R,6))
np.round(Q@R,5)

[[-0.707107  0.707107  0.      ]
 [-0.        0.       -1.      ]
 [-0.707107 -0.707107  0.      ]]
[[-1.414214 -0.707107 -0.707107]
 [ 0.       -2.12132   0.707107]
 [ 0.        0.       -2.      ]]


array([[ 1., -1.,  1.],
       [ 0.,  0.,  2.],
       [ 1.,  2., -0.]])

In [4]:
L=np.array([[1,0,0],[-1.,1,0],[1,2,2.],[1,1,1]])
U=np.array([[2,1,-1,0,3.],[0,1,1,-2.,3.],[0,0,-1,2,1.]])   
B=L@U
print(B)

[[ 2.  1. -1.  0.  3.]
 [-2.  0.  2. -2.  0.]
 [ 2.  3. -1.  0. 11.]
 [ 2.  2. -1.  0.  7.]]


In [5]:
np.linalg.matrix_rank(B)

3

In [6]:
B.shape

(4, 5)

In [7]:
Q,R=np.linalg.qr(B,mode='reduced')  #direktiva za redukovanu QR
print(np.round(Q,6))
print(np.round(R,6))
np.round(Q@R,5)

[[-0.5       0.223607  0.730297 -0.408248]
 [ 0.5      -0.67082   0.547723  0.      ]
 [-0.5      -0.67082  -0.365148 -0.408248]
 [-0.5      -0.223607  0.182574  0.816497]]
[[ -4.        -3.         2.5       -1.       -10.5     ]
 [  0.        -2.236068  -0.67082    1.341641  -8.273452]
 [  0.         0.         0.547723  -1.095445  -0.547723]
 [  0.         0.         0.        -0.        -0.      ]]


array([[ 2.,  1., -1.,  0.,  3.],
       [-2.,  0.,  2., -2.,  0.],
       [ 2.,  3., -1., -0., 11.],
       [ 2.,  2., -1.,  0.,  7.]])

In [8]:
Q,R=np.linalg.qr(B)  #direktiva za punu QR
print(np.round(Q,6))
print(np.round(R,6))
np.round(Q@R,5)

[[-0.5       0.223607  0.730297 -0.408248]
 [ 0.5      -0.67082   0.547723  0.      ]
 [-0.5      -0.67082  -0.365148 -0.408248]
 [-0.5      -0.223607  0.182574  0.816497]]
[[ -4.        -3.         2.5       -1.       -10.5     ]
 [  0.        -2.236068  -0.67082    1.341641  -8.273452]
 [  0.         0.         0.547723  -1.095445  -0.547723]
 [  0.         0.         0.        -0.        -0.      ]]


array([[ 2.,  1., -1.,  0.,  3.],
       [-2.,  0.,  2., -2.,  0.],
       [ 2.,  3., -1., -0., 11.],
       [ 2.,  2., -1.,  0.,  7.]])

Vidimo da je ugrađena funkcija NumPy biblioteke implementirana na način zbog koga  dobijena QR faktorizacija sugeriše da je $A$ možda matrica ranga $4.$ Slično radi i ugrađena funkcija modula SciPy.

In [9]:
from scipy.linalg import qr

In [10]:
Q,R=qr(B, mode='economic')
print(np.round(Q,6))
print(np.round(R,6))
np.round(Q@R,5)

[[-0.5       0.223607  0.730297 -0.408248]
 [ 0.5      -0.67082   0.547723  0.      ]
 [-0.5      -0.67082  -0.365148 -0.408248]
 [-0.5      -0.223607  0.182574  0.816497]]
[[ -4.        -3.         2.5       -1.       -10.5     ]
 [  0.        -2.236068  -0.67082    1.341641  -8.273452]
 [  0.         0.         0.547723  -1.095445  -0.547723]
 [  0.         0.         0.        -0.        -0.      ]]


array([[ 2.,  1., -1.,  0.,  3.],
       [-2.,  0.,  2., -2.,  0.],
       [ 2.,  3., -1., -0., 11.],
       [ 2.,  2., -1.,  0.,  7.]])

In [11]:
Q,R=qr(B)
print(np.round(Q,6))
print(np.round(R,6))
np.round(Q@R,5)

[[-0.5       0.223607  0.730297 -0.408248]
 [ 0.5      -0.67082   0.547723  0.      ]
 [-0.5      -0.67082  -0.365148 -0.408248]
 [-0.5      -0.223607  0.182574  0.816497]]
[[ -4.        -3.         2.5       -1.       -10.5     ]
 [  0.        -2.236068  -0.67082    1.341641  -8.273452]
 [  0.         0.         0.547723  -1.095445  -0.547723]
 [  0.         0.         0.        -0.        -0.      ]]


array([[ 2.,  1., -1.,  0.,  3.],
       [-2.,  0.,  2., -2.,  0.],
       [ 2.,  3., -1., -0., 11.],
       [ 2.,  2., -1.,  0.,  7.]])

Treba biti oprezan sa upotrebom ovih ugrađenih funkcija.

***

**Zadatak 1.** Odrediti broj aritmetičkih operacija neophodnih za modifikovanu QR dekompoziciju Gram-Šmitovim postupkom regularne matrice $A\in\mathcal{M}_{n\times n}.$	

**Rešenje :**

Postupak QR faktorizacije podrazumeva izračunavanje kvadratnog korena. Iako je $\sqrt{\phantom{w}}$ zapravo poziv podrutine, tretiraćemo ga kao jednu aritemetičku operaciju, zbog olakšavanja analize.

Za lakše prebrojavanje operacija iskoristićemo međurezultate:
- Jedan skalarni proizvod dva vektora dimenzije $n$ troši $n$ množenja i $n-1$ sabiranja, što je ukupno $2n-1$ operacija.
- Izračunavanje norme vektora dimenzije $n$ koristi jedan skalarni proizvod vektora sa samim sobom i jedno korenovanje, što je ukupno $2n$ operacija.
- Normiranje vektora dimenzije $n$ podrazumeva izračunavanje njegove orme i skaliranje komponenti: $3n$ operacija.
- Jedan proizvod ${\rm vektor}_{n\times1}^T \cdot\ {\rm matrica}_{n\times(n-k)}$ podrazumeva $n-k$ skalarnih proizvoda vektora dimenzije $n,$ što je ukupno $(n-k)(2n-1)$ operacija.

U $k-$tom koraku Gram-Šmitovog postupka, ulazni podaci su
$$ a_k\in\mathbb{R}^n,\quad Q_{k}\in\mathcal{M}_{n\times(n-k)},\quad
R_{k}\in\mathcal{M}_{(n-k)\times(n-k)}.$$

Izračunavanja u $k-$tom koraku:
- Normiranje vektora $a_k$ za dobijanje vektora $q_k.$ Broj operacija je $3n.$
- Furijeovi koeficijenti: $r_{k}^T=q_k^TQ_{k};$ operacije $=(n-k)(2n-1).$
- Ažuriranje vektora matrice $Q_{k}:$ $Q_k:=Q_k-q_kr_k^T.$ Broj operacija je  $2n(n-k).$

Zaključujemo da je broj operacija $k-$tog koraka $f(k)=3n+(n-k)(2n-1)+2n(n-k)=3n+(n-k)(4n-1)=4n^2-2n(2k-1)+k.$

Ukupan broj operacija svih $n$ koraka je tada $S_n=\displaystyle\sum_{k=1}^n\Big(4n^2-2n(2k-1)+k\Big)=2n^3+\dfrac12n^2+\dfrac{1}{2}n\,.$

***

**Zadatak 2.** Neka je $A\in\mathcal{M}_{n\times m}$ matrica punog ranga kolona. Poznata je faktorizacija Čoleskog Gramove matrice $A^TA=LL^T.$ Označimo  $Q=A(L^T)^{-1}.$ Pokazati da je matrica $Q$ sa ortogonalnim kolonama. Na osnovu dokazanog uspostaviti vezu između $QR$ faktorizacije matrice $A$ i faktorizacije Čoleskog matrice $A^TA.$	

**Rešenje :**

$Q=A(L^T)^{-1}\in\mathcal{M}_{n\times m}$ ima ortogonalne kolone $\quad\Longleftrightarrow\quad$ $Q^TQ=I_m.$

$$Q^TQ=\left(A(L^T)^{-1}\right)^TA(L^T)^{-1}=L^{-1}(A^TA)(L^T)^{-1}\stackrel{A^TA=LL^T}{=}
L^{-1}(LL^T)(L^T)^{-1}=I_m.$$
Zaključujemo:
$ A=QR\quad \Longrightarrow\quad A^TA=R^TR$ je faktorizacija Čoleskog za $L=R^T.$

***

**Zadatak 3.** Kvadratna matrica $A$ reda $n$ ima faktorizaciju $A=QR$ gde je $Q$ orotogonalna matrica i $R$ gornje trougaona. Dokazati jednakosti $$A^TA=R^TR,\qquad	\det(A^TA)=\det(R)^2.$$

**Rešenje :**

$A\in\mathcal{M}_{n\times n},\ A=QR,\ \Longrightarrow\ Q,R\in\mathcal{M}_{n\times n}$
\begin{align}
A^TA&=(QR)^TQR=R^T\underbrace{Q^TQ}_{I_n}R=R^TR,\\
\det(A^TA)&=\det(R^TR)=\det(R^T)\det(R)=\det(R)^2.
\end{align}

***

## Izbor pivot elementa

Zbog stabilnosti u izračunavanjima, tačnije da bi se izbegao eksponencijalni rast vrednosti unutar matrice, primenjuje se postupak $QR$ faktorizacije sa izborom pivot elementa.  Cilj pivot strategije je postavljanje elemenata sa maksimalnim modulom na dijagonalu matrice $R.$ To se postiže permutacijom kolona matrice $A$ tako da pivot kolona (kolona u odnosu na koju se sprovode sva izračunavanja te iteracije) bude uvek vektor najveće norme. Konačan rezultat ovakve dekompozicije je tada $$AP=QR,\quad\mbox{ tj. }\quad A=QRP^T,$$ gde je $P$ odgovarajuća permutaciona matrica, a $R$ je trougaona matrica kod koje za dijagonalne elemente važi: 
$$|r_{00}|\geq|r_{11}|\geq\dots\geq|r_{kk}|\geq\dots.$$

Geometrijski posmatrano, strategija izbora pivot vektora u ortogonalnoj dekompoziciji služi da se pronađe vektor koji je 'najviše' linearno nezavisan u odnosu na prethodno generisane vektore - ima najveće odstojanje od potprostora razapetog nad prethodno generisanim vektorima. Na taj način njegovom ortogonalizacijom dobija se vektor koji je u toj iteraciji najdalje od nula-vektora. To je bitan kriterijum jer normiranjem vektora bliskog nuli dobili bi se numerički veoma nepouzdani rezultati.

Pivot strategija kod klasičnog Gram-Šmitovog postupka ne daje adekvatno kvalitetnije rezultate. Redosled normi vektora sa ulaza koji se utvrdi na početku algoritma ne menja se tokom iteracija jer se ulazni vektori menjaju samo jedan po jedan u svakom koraku. Zbog toga ovu strategiju kod klasičnog Gram-Šmit algoritma ne analiyiramo. Sa druge strane, izbor pivot elementa čini modifikovani Gram-Šmitov postupak dodatno numerički tačnijim (pouzdanijim) u odnosu na klasičan Gram-Šmitov postupak. Razlog leži upravo u stalnom ažuriranju vektora nad kojima se projekcije u nastavku vrše. Naravno, svaka pivot strategija unutar algoritma povećava i njegove memorijske i operacijske zahteve. Ipak, s obzirom na kvalitet generisanih rezultata, ovakvi dodaci jesu veoma korisni/isplativi naročito pri radu sa matricama većih dimenzija. Opis strategije pivot kolona kod modifikovanog Gram-Šmitovog postupka dat je u nastavku.

U prvom koraku Gram-Šmitovog algoritma odrede se norme svih vektora kolona matrice $A\in\Me_{\mn},$
$$A=\left[\begin{array}{c|c|c|c}
\!\!\begin{array}{c}\phantom{i}\\a_0\\\phantom{i}\end{array}\!\!
&\,a_1\,&\dots&a_{n-1} \end{array}\right],\qquad
norme=\begin{bmatrix}\|a_0\|^2&\|a_1\|^2&\dots&\|a_{n-1}\|^2\end{bmatrix}.$$
Na osnovu indeksa najveće komponente vektora $norme$ bira se prva pivot kolona, vrši se odgovarajuća permutacija kolona matrice $A$ i kolona vektora $norme.$
To ćemo zbog jednostavnosti zapisa tretirati kao prenumeraciju indeksa odgovarajućih vektora, tj. 
\begin{align}
 \left[\begin{array}{c|c|c|c}
\begin{array}{c}\phantom{i}\\
\!a_0\\\phantom{i}\end{array}\
&\,a_1\,&\dots&a_{n-1} \end{array}\right]&\mapsto
\left[\begin{array}{c|c|c|c}
\begin{array}{c}\phantom{i}\\
\!a_0'\\\phantom{i}\end{array}\
&\,a_1'\,&\dots&a_{n-1}' \end{array}\right],\\[10pt]
\begin{bmatrix}\ \|a_0\|^2&\|a_1\|^2&\dots&\|a_{n-1}\|^2\ \end{bmatrix}&\mapsto
\begin{bmatrix}\ \|a_0'\|^2&\|a_1'\|^2&\dots&\|a_{n-1}'\|^2\ \end{bmatrix}.
\end{align}

Zbog toga zanemarićemo oznake $'$ u $a_k'.$
Normiranjem se kreira prvi vektor $q_0$ i popunjava prva vrsta matrice $R$ odgovarajućim Furijeovim koordinatama $q_0^Ta_k,\ k=1,\dots,n-1.$
Zatim se kreiraju vektori $u_{k0}=a_k-(q_0^Ta_k)q_0,\ k=1,\dots,n-1.$ 
Na osnovu uopštene Pitagorine teoreme za Furijeove koeficijente, za norme vektora $u_{k0}$ važi $$\|u_{k0}\|^2=\|a_k\|^2-(q_0^Ta_k)^2.$$  Primetimo nejednakosti:
$$\|u_{k0}\|^2\leq\|a_k\|^2\leq\|a_0\|^2\ \Longleftrightarrow\ \|u_{k0}\|\leq\|a_k\|\leq\|a_0\|,\quad k=1,\dots,n-1.$$
Na taj način se zaista obezbeđuje uslov opadanja normi prilikom izgradnje ortogonalne faktorizacije.

Adekvatnim ažuriranjem odgovarajućih komponenti vektora $norme$ imamo uvid u sledeći izbor pivot elementa:
\begin{align}
 &\begin{bmatrix}\ \|a_0\|^2&\|a_1\|^2&\dots&\|a_{n-1}\|^2\ \end{bmatrix}-
 \begin{bmatrix}0&(q_0^Ta_1)^2&\dots&(q_0^Ta_{n-1})^2\end{bmatrix}\\ &\qquad\mapsto\ 
 \begin{bmatrix}\ \|a_0\|^2&\|u_{10}\|^2&\dots&\|u_{n-1\,0}\|^2\ \end{bmatrix}.
\end{align}
Za pivot kolonu bira se vektor $u_{k0}, \ k\in\{1,\dots,n-1\}$ maksimalne norme. Izvrši se odgovarajuća permutacija vektora $u_{k0}$ i prema tome i permutacija komponenti vektora $norme.$ Time počinje naredni korak modifikovanog Gram-Šmitovog algoritma. Normiranjem $q_1=\dfrac{u_{k0}}{\|u_{k0}\|}$ dobija se nova kolona matrice $Q.$ Na osnovu Furijeovih koordinata ažuriraju se ulazni vektori i njihove norme:
$$u_{k1}=u_{k0}-(q_1^Tu_{k0})q_1,\qquad \|u_{k1}\|^2=\|u_{k0}\|^2-(q_1^Tu_{k0})^2,\qquad k=2,\dots,n-1,$$
$$\begin{bmatrix}\  \|a_0\|^2&\|u_{10}\|^2&\|u_{20}\|^2&\dots&\|u_{n-1\,0}\|^2\ \end{bmatrix}\ \mapsto\ 
\begin{bmatrix}\ \|a_0\|^2&\|u_{10}\|^2&\|u_{21}\|^2&\dots&\|u_{n-1\,1}\|^2\ \end{bmatrix}.$$

Nastavljajući opisani postupak uz ažuriranje vektora normi kroz sve naredne korake modifikovanog Gram-Šmitovog postupka dobija se njegova varijanta sa izborom pivot elementa.

***